//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsIndicadoresEconomicos
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.sdde.bccr.fi.cr", ConfigurationName="WsIndicadoresEconomicos.wsindicadoreseconomicosSoap")]
    public interface wsindicadoreseconomicosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosResponse> ObtenerIndicadoresEconomicosAsync(WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosXMLResponse> ObtenerIndicadoresEconomicosXMLAsync(WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerIndicadoresEconomicos", WrapperNamespace="http://ws.sdde.bccr.fi.cr", IsWrapped=true)]
    public partial class ObtenerIndicadoresEconomicosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=0)]
        public string Indicador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=1)]
        public string FechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=2)]
        public string FechaFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=3)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=4)]
        public string SubNiveles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=5)]
        public string CorreoElectronico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=6)]
        public string Token;
        
        public ObtenerIndicadoresEconomicosRequest()
        {
        }
        
        public ObtenerIndicadoresEconomicosRequest(string Indicador, string FechaInicio, string FechaFinal, string Nombre, string SubNiveles, string CorreoElectronico, string Token)
        {
            this.Indicador = Indicador;
            this.FechaInicio = FechaInicio;
            this.FechaFinal = FechaFinal;
            this.Nombre = Nombre;
            this.SubNiveles = SubNiveles;
            this.CorreoElectronico = CorreoElectronico;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerIndicadoresEconomicosResponse", WrapperNamespace="http://ws.sdde.bccr.fi.cr", IsWrapped=true)]
    public partial class ObtenerIndicadoresEconomicosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=0)]
        public WsIndicadoresEconomicos.ArrayOfXElement ObtenerIndicadoresEconomicosResult;
        
        public ObtenerIndicadoresEconomicosResponse()
        {
        }
        
        public ObtenerIndicadoresEconomicosResponse(WsIndicadoresEconomicos.ArrayOfXElement ObtenerIndicadoresEconomicosResult)
        {
            this.ObtenerIndicadoresEconomicosResult = ObtenerIndicadoresEconomicosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerIndicadoresEconomicosXML", WrapperNamespace="http://ws.sdde.bccr.fi.cr", IsWrapped=true)]
    public partial class ObtenerIndicadoresEconomicosXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=0)]
        public string Indicador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=1)]
        public string FechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=2)]
        public string FechaFinal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=3)]
        public string Nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=4)]
        public string SubNiveles;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=5)]
        public string CorreoElectronico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=6)]
        public string Token;
        
        public ObtenerIndicadoresEconomicosXMLRequest()
        {
        }
        
        public ObtenerIndicadoresEconomicosXMLRequest(string Indicador, string FechaInicio, string FechaFinal, string Nombre, string SubNiveles, string CorreoElectronico, string Token)
        {
            this.Indicador = Indicador;
            this.FechaInicio = FechaInicio;
            this.FechaFinal = FechaFinal;
            this.Nombre = Nombre;
            this.SubNiveles = SubNiveles;
            this.CorreoElectronico = CorreoElectronico;
            this.Token = Token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerIndicadoresEconomicosXMLResponse", WrapperNamespace="http://ws.sdde.bccr.fi.cr", IsWrapped=true)]
    public partial class ObtenerIndicadoresEconomicosXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.sdde.bccr.fi.cr", Order=0)]
        public string ObtenerIndicadoresEconomicosXMLResult;
        
        public ObtenerIndicadoresEconomicosXMLResponse()
        {
        }
        
        public ObtenerIndicadoresEconomicosXMLResponse(string ObtenerIndicadoresEconomicosXMLResult)
        {
            this.ObtenerIndicadoresEconomicosXMLResult = ObtenerIndicadoresEconomicosXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface wsindicadoreseconomicosSoapChannel : WsIndicadoresEconomicos.wsindicadoreseconomicosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class wsindicadoreseconomicosSoapClient : System.ServiceModel.ClientBase<WsIndicadoresEconomicos.wsindicadoreseconomicosSoap>, WsIndicadoresEconomicos.wsindicadoreseconomicosSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsindicadoreseconomicosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsindicadoreseconomicosSoapClient.GetBindingForEndpoint(endpointConfiguration), wsindicadoreseconomicosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsindicadoreseconomicosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsindicadoreseconomicosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsindicadoreseconomicosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsindicadoreseconomicosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsindicadoreseconomicosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosResponse> ObtenerIndicadoresEconomicosAsync(WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosRequest request)
        {
            return base.Channel.ObtenerIndicadoresEconomicosAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosXMLResponse> ObtenerIndicadoresEconomicosXMLAsync(WsIndicadoresEconomicos.ObtenerIndicadoresEconomicosXMLRequest request)
        {
            return base.Channel.ObtenerIndicadoresEconomicosXMLAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsindicadoreseconomicosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsindicadoreseconomicosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsindicadoreseconomicosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://gee.bccr.fi.cr/Indicadores/Suscripciones/WS/wsindicadoreseconomicos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsindicadoreseconomicosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://gee.bccr.fi.cr/Indicadores/Suscripciones/WS/wsindicadoreseconomicos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsindicadoreseconomicosSoap,
            
            wsindicadoreseconomicosSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.1.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
